### ISSUE TITLE
Seti_UX color scheme port JetBrains products.

### ISSUE THREAD

**Issue by zchee** [zchee/Seti_JetBrains#1]
I created tentatively issue.
Come on @ctf0 , @ikeagold .

 I'll commit tentatively icls file.
plz wait.

**Comment by zchee** [comment]
@ctf0 
Thanks. :)
Now I'm doing various behind the scenes.

Don't Miss It!

**Comment by zchee** [comment]
@ctf0 
Thanks add README in
https://github.com/ctf0/Seti_ST3/commit/d7d56c16673a2639033709469773e4cbe499e7e0
: )

**Comment by ctf0** [comment]
np ,hard work deserve credits.

**Comment by danielgomezrico** [comment]
I cant find Seti_JB plugin with Android Studio :(

**Comment by zchee** [comment]
@danielgomezrico
Oh, I'll build and upload now!
What are you using Android Studio version ?

**Comment by danielgomezrico** [comment]
`1.2.1.1`

**Comment by zchee** [comment]
Forwarded https://github.com/zchee/Seti_JetBrains/issues/9
Wait a little!
