### ISSUE TITLE
AppCode not loading Seti_JB.icls

### ISSUE THREAD

**Issue by evliu** [zchee/Seti_JetBrains#10]
I get an error trying to load this color theme into AppCode, ideas?

**Comment by zchee** [comment]
@evliu I'll try later. 
Please wait a little :)

BTW, Would you write your environment?
OS, AppCode ver, or etc...

**Comment by evliu** [comment]
thx! Mac OS X 10.10.3, java version "1.6.0_65", newest AppCode

**Comment by zchee** [comment]
@evliu Ok, I'll try later...

**Comment by zchee** [comment]
@evliu 
I fix now. 
The cause was this version specified.
https://github.com/zchee/Seti_JetBrains/commit/e90eb04f4055a4c2dfcb825de24a6fce463d0c5e#diff-b1d97b1d095a987ff956c4dd59d429fcL1 .

Please try again!!

**Comment by evliu** [comment]
Works, thanks!
