### ISSUE TITLE
AppCode 3.1.7 Support

### ISSUE THREAD

**Issue by evliu** [zchee/Seti_JetBrains#13]
Jetbrains just released AppCode 3.1.7 :) thx!

**Comment by zchee** [comment]
Ok :)

**Comment by zchee** [comment]
@evliu I'm writing automation build for jar using `Docker`.
Please wait a little :)

**Comment by evliu** [comment]
No problem! I was just thinking of a deploy shell script of some kind

**Comment by zchee** [comment]
@evliu Oh! Would you show me a code(or gist)?

**Comment by evliu** [comment]
i don't have any, haha, just thought about it, but i don't even know how your extension works :P but i'm guessing you're just swapping files out of the jar, but i just haven't had time to look at exactly what is happening.

**Comment by zchee** [comment]
@evliu Sorry...I'm writing other project.
Please wait a little longer :(

**Comment by evliu** [comment]
No rush, it's only for the colors so it's not crucial to my coding

**Comment by zchee** [comment]
Sorry for late reply :(
Update Appcode 3.2.0 :tada:
https://github.com/zchee/Seti_JetBrains/commit/a15c1b50327e78361e4905a9b264593dab3cd755

**Comment by evliu** [comment]
Thanks!

**Comment by evliu** [comment]
What needs to be done when a new version comes out? Maybe I can figure out some simple way to automate it. Do you just swap out a few files in the jar? Thx

**Comment by zchee** [comment]
@evliu :)
Please create issue!
