### ISSUE TITLE
Darcula don't change PHPStorm 8.0.3 build 139.1348

### ISSUE THREAD

**Issue by silasrm** [zchee/Seti_JetBrains#14]
https://www.dropbox.com/s/c1cmm2tj9o535a4/Screenshot%202015-06-23%2009.20.34.png?dl=0

Icons and Color Scheme is ok. But Darcula modifications don't change this version.

**Comment by zchee** [comment]
OK! I'll check later :)

**Comment by zchee** [comment]
@silasrm What PHPStorm version?

**Comment by zchee** [comment]
Release PhpStorm 9 EAP 141.1717.
https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Early+Access+Program
https://github.com/zchee/Seti_JetBrains/commit/c6ff57bec6f79a884f96ec6aabdf80904934d3ea

Would you try again?

**Comment by silasrm** [comment]
Not. My PHPStorm is licensed by the company I'm working.
I won't change to EAP version.

Thank's.

**Comment by zchee** [comment]
@silasm Ok.
I'll relaease not eap version later :)

**Comment by silasrm** [comment]
Very Thank's!

**Comment by zchee** [comment]
@silasrm 
Hey!
https://github.com/zchee/Seti_JetBrains/commit/3a2ddc47735e288b562393bc5bcc5f55e7107f79

**Comment by silasrm** [comment]
Don't change anything hear: https://www.dropbox.com/s/7tq0m4xm7ybikxy/Screenshot%202015-06-25%2013.41.54.png?dl=0

:(

**Comment by silasrm** [comment]
After refresh, PHPStorm is not running more: https://www.dropbox.com/s/rn4pa8xpqq2vrfn/Screenshot%202015-06-25%2013.52.26.png?dl=0
I'll test EAP version. If not OK, I'll using color scheme only.

Thk's for try help me.

**Comment by silasrm** [comment]
On EAP :( https://www.dropbox.com/s/4qgp204uueh0fpm/Screenshot%202015-06-25%2015.32.51.png?dl=0

The size is different: 
- Original https://www.dropbox.com/s/ojf2gt2lnhkfexw/Screenshot%202015-06-25%2015.34.43.png?dl=0
- Edited https://www.dropbox.com/s/m9x51atxf1anvho/Screenshot%202015-06-25%2015.34.54.png?dl=0

I'll be using color scheme only. Thank's!
