### ISSUE TITLE
Forwarded evliu's issue

### ISSUE THREAD

**Issue by zchee** [zchee/Seti_JetBrains#15]
@evliu
https://github.com/zchee/Seti_JetBrains/issues/13#issuecomment-114274082
> What needs to be done when a new version comes out? Maybe I can figure out some simple way to automate it. Do you just swap out a few files in the jar? Thx

**Comment by evliu** [comment]
Sorry, I've been quite busy just as you are. What do you usually manually do when a new version comes out? I'm guessing you download the new version of IntelliJ/AppCode/etc, grab the .jar file, and swap out some files, but I don't know the steps exactly. If you can let me know the steps, I can try to write a shell script to do it. Thx

**Comment by zchee** [comment]
@evliu Sorry late reply.
I stayed away from the little Intellij.
but, I came back!!

When I update the Seti_JetBrains's jar, I am doing this workflow manually. [CONTRIBUTING.md](https://github.com/zchee/Seti_JetBrains/blob/master/CONTRIBUTING.md)
I tried make the specific shell script.
Yes, shell script is very good, but can not test.
Resulting in https://github.com/zchee/Seti_JetBrains/issues/16

So, I'm thinking the new Idea. Docker Orchestrations with any CI (Travis-CI or CircleCI or Wercker.)
and, Docker with "GUI"
FYI, https://blog.jessfraz.com/post/docker-containers-on-the-desktop/ in "GUIs"

but, Dockerfile are also similar to the shell script.
If you have time, I want to teaching to write a shell script :)

**Comment by evliu** [comment]
I'll take a look when I get back from my honeymoon!

**Comment by zchee** [comment]
@evliu 
Oh! Happy honeymoon!! :tada::tada:

BTW, I work hard, I wrote Dockerfile and circle.yml for all Intellij IDEs.
They are, Parses the commit message, and if find `[idea/***.**.*]`, automatically built using Docker in CircleCI.
After that, it has to be pushed to automatically github release.

How do you like it? :)
