### ISSUE TITLE
Needs update for PHPStorm 9

### ISSUE THREAD

**Issue by apertureless** [zchee/Seti_JetBrains#17]
PHPStorm 9 got released recently, and the theme needs an update for build 141.1912.

**Comment by brandonferens** [comment]
+1

**Comment by danjuls** [comment]
+1

**Comment by zchee** [comment]
@apertureless @brandonferens @danjuls 
Sorry, I stayed away from the little Intellij.
but, I came back!!

I'll update later :)

**Comment by zchee** [comment]
Update!!
https://github.com/zchee/Seti_JetBrains/commit/3bf11b93ce3141d61ce6f02dd1d4da6b1610efe2

**Comment by brandonferens** [comment]
Not sure if this is a PHPStorm 9 issue or not, but when attempting to load the icons, I get the following error:
```
Fail to load plugin descriptor from file Seti_JB-icons.jar
```

**Comment by zchee** [comment]
@apertureless @brandonferens @danjuls 
Upgraded!!
jar is move to Github Release.
See https://github.com/zchee/Seti_JetBrains/releases/tag/phpstorm%2F9.0.2

and, Close issue.
