### ISSUE TITLE
Change filetype icons

### ISSUE THREAD

**Issue by zchee** [zchee/Seti_JetBrains#2]
Reference:
https://www.jetbrains.com/phpstorm/help/file-types-recognized-by-phpstorm.html
https://www.jetbrains.com/phpstorm/help/creating-and-registering-file-types.html
https://www.jetbrains.com/phpstorm/help/file-types.html

**Comment by ikeagold** [comment]
Thanx for php :) works excellent! Great work!
And i see filesize was changed from 14mb to 5mb (windows) its nice too!
