### ISSUE TITLE
idea.jar files missing for all platforms except android studio

### ISSUE THREAD

**Issue by metaColin** [zchee/Seti_JetBrains#22]
Looks like some of the idea.jar files are no longer in the repo.

The /theme/ folder should contain jar files for every supported platform (e.g. WebStorm, PHPStorm, etc) but right now there is only an idea.jar file for Android Studio.

Please include the missing files.

**Comment by evliu** [comment]
+1

**Comment by zchee** [comment]
@metaColin @evliu 
What?

**Comment by zchee** [comment]
@metaColin For example, do you want to change the look of any IDE?

**Comment by evliu** [comment]
Where can we download appcode.jar in the repo?

**Comment by zchee** [comment]
@evliu thanks fast reply. 
For example, AppCode RC2 is https://github.com/zchee/Seti_JetBrains/releases/tag/appcode%2F141.2456.7. 
All IDE download page is https://github.com/zchee/Seti_JetBrains/releases

If you want the AppCode EAP 3.3 (build 142.4675.7), I will later release.

**Comment by metaColin** [comment]
@zchee your instructions are difficult to understand. Please update to explain how to download different versions of the repository.

**Comment by zchee** [comment]
@metaColin 
Wait,wait.
Do you want to change the look of any IDE?
Android Studio?

**Comment by zchee** [comment]
@metaColin
If you give me time, I will offer a version of the jar that you desire. And I will tell you why you would change the release method

**Comment by metaColin** [comment]
@zchee you do not understand the problem that I am trying to describe. Ask someone who speaks fluent english to help translate this.

**Comment by metaColin** [comment]
@zchee the answer you gave @evliu answers the question. But this is not clear in the instructions, please consider making more detailed installation instructions.

**Comment by zchee** [comment]
@metaColin Thanks reply.

Ok.
So, I will later update the readme.
Thanks Advise!!
