### ISSUE TITLE
Docker process

### ISSUE THREAD

**Issue by evliu** [zchee/Seti_JetBrains#23]
Hi, i'm not familiar with the process you use to create the jars. I've tried to spin up a linux environment and run the docker file but it didn't save the jar anywhere. would you be able to do a screencast of the process?

**Comment by zchee** [comment]
Yes, wait a little :)

**Comment by zchee** [comment]
https://www.youtube.com/watch?v=5sH3Yjg9aec

**Comment by zchee** [comment]
@evliu 
Or, https://asciinema.org/a/deh5qkfedieg9muk580801tvl

**Comment by evliu** [comment]
Ahh I c, I didn't know how to extract the jar from Docker. I was trying on Digital Ocean ubuntu instance

**Comment by zchee** [comment]
Use `cat` docker hack :)
Close.

**Comment by zchee** [comment]
@evliu BTW, Also, please post the issue if there are any problems :)
