### ISSUE TITLE
Webstorm 11 is released.

### ISSUE THREAD

**Issue by geraldyeo** [zchee/Seti_JetBrains#27]
Webstorm 11 is released recently, and the webstorm.jar for 11 eap is not usable.

**Comment by badabam** [comment]
I need this! Without Seti, Webstorm is so ugly.

**Comment by Chyngyz** [comment]
+++++ Neeed this

**Comment by zchee** [comment]
@geraldyeo @badabam @Chyngyz 
Ok, ok... :)
I'll commit later !!

**Comment by zchee** [comment]
@geraldyeo @badabam @Chyngyz 
See https://github.com/zchee/Seti_JetBrains/releases
Merry Christmas !!
