### ISSUE TITLE
I can't seem to get this working with Webstorm 10

### ISSUE THREAD

**Issue by mikeerickson** [zchee/Seti_JetBrains#6]
Do you have any additional tips, etc. on getting this to work with Webstorm 10?

I have completed each of the steps and restarted Webstorm, however, it still uses my previous theme?  Should I be doing something else within Webstorm (theme still shows KS_Black which was my original theme).

**Comment by zchee** [comment]
@mikeerickson
Thanks issue.

I will support you as much as possible.
First, What do you using os distribution?

**Comment by mikeerickson** [comment]
I am working on OSX using WebStorm 10 EAP (and will continue when it becomes final)

**Comment by mikeerickson** [comment]
@zchee If you need any details from me about where I placed things, etc.  I have supplied below

http://d.pr/i/1eFrk

**Comment by zchee** [comment]
@mikeerickson 
thanks.
Still I did not correspond to the now of WebStorm EAP.

I build now !!
Please wait :)

**Comment by zchee** [comment]
I pushed webstorm 141.614 now.

1. Download [webstorm](https://github.com/zchee/Seti_JetBrains/blob/master/theme/webstorm/mac/141.614/webstorm.jar)
2. Replace `idea.jar` to `/Applications/WebStorm 10 EAP.app/Contents/lib/`. **Not replace icon.jar**
3. If you want replace icons, see [Installation - Icons](https://github.com/zchee/Seti_JetBrains#icons)

**Comment by ikeagold** [comment]
@zchee I see you switched to Mac and Ruby (as I see from your starred timeline) thanks for that fix too. I now using EAPs too, like you do) but I use phpstorm, thinking to switch on web storm because 2much work on front end and etc.

**Comment by zchee** [comment]
@ikeagold 
Long time no see!

I'm Mac and Ruby from previous.
I using Idea Ultimate (for Java and Go), RubyMine (for Ruby and Rails) and WebStorm (for Typescript and JavaScript).
But, I'm going to also corresponds to the other distributions I felt that if you post a isuue :)

**Comment by ikeagold** [comment]
No thanx, i think im leave a windows soon as possible from my home pc (because on a work and other places i prefer Linux Mint or MacOS). And currently use a modified version of your work, i colorized that theme with some another colors from my favourite game (World of Warcraft) i used class colors on color scheme icls file and using that =).

I thinking about Atom.io :atm: , maybe in future its fully replace any other Idea IDE =)

**Comment by mikeerickson** [comment]
@zchee I have done what you have outlined above, replacing the application webstorm.jar with the downloaded file and now I receive the following error when launching Webstorm 10

http://d.pr/i/WnTS

**Comment by zchee** [comment]
@ikeagold
Sorry i don't understand :(
> Whats app you use in github dev programm?

**Comment by ikeagold** [comment]
@zchee ow, sorry: What application or project type you use in GitHub Developer Program (i found this badge in your profile "Developer Program Member").

**Comment by zchee** [comment]
@ikeagold
You might have misunderstood a little :)
"Developer Program Member" badge is anyone should get used if pay money to github.
See https://github.com/pricing and https://developer.github.com/program/

**Comment by zchee** [comment]
It was resolved individually corresponding to mikeerickson.
