### ISSUE TITLE
AppCode

### ISSUE THREAD

**Issue by evliu** [zchee/Seti_JetBrains#7]
Hi, would you be willing to make a version for AppCode? Thanks!

**Comment by zchee** [comment]
Yeah !
https://github.com/zchee/Seti_JetBrains/commit/53ae180c1826769727b5f6d271a4cc77b5287f73

**Comment by zchee** [comment]
@evliu Do you want a Windows version? Please comment.

**Comment by evliu** [comment]
mac ;) I don't think there is a AppCode for Windows, haha, since it's for making iOS and Mac apps :P

**Comment by zchee** [comment]
@evliu lol
closed.
