### ISSUE TITLE
Support Andriod Studio latest version(1.2.1.1)

### ISSUE THREAD

**Issue by zchee** [zchee/Seti_JetBrains#9]
See also https://github.com/zchee/Seti_JetBrains/issues/1#issuecomment-104700141
I will build idea.jar for Andriod Studio latest version, and
Seti_JB (replace icon) plugin.

**Comment by zchee** [comment]
@danielgomezrico say
Android Studio 1.2.1.1

https://github.com/zchee/Seti_JetBrains/issues/1#issuecomment-104796718

**Comment by zchee** [comment]
@danielgomezrico
I pushed 2 commit.
and, Works fine on Android Studio Canary for Mac!
https://github.com/zchee/Seti_JetBrains/commit/3b54e31c9fb4c96945b665c2a4a986f7da3322b7

**Comment by danielgomezrico** [comment]
Still can´t find it in the plugins list, where is it?

**Comment by zchee** [comment]
@danielgomezrico 
Hmm...
Please direct message on twitter?

**Comment by zchee** [comment]
@danielgomezrico Or, try https://github.com/zchee/Seti_JetBrains#icons ?

**Comment by zchee** [comment]
@danielgomezrico ping! :)

**Comment by zchee** [comment]
Close...

**Comment by danielgomezrico** [comment]
Excuse me, didn´t try it.

**Comment by zchee** [comment]
@danielgomezrico Oh, sorry :)
Do you have trouble with anything, please tell me again.

**Comment by danielgomezrico** [comment]
@zchee Just read that white styles are easy to read than back ones. What do you think?

**Comment by zchee** [comment]
@danielgomezrico ??

**Comment by danielgomezrico** [comment]
I lose interest on changing this. Excuse me. :+1:
